artifact_location: file:///C:/Users/%D0%9D%D0%B0%D1%80%D0%B3%D0%B8%D1%81/PycharmProjects/karaganda_eval/pipelines/mlruns/0
creation_time: 1710761446288
experiment_id: '0'
last_update_time: 1710761446288
lifecycle_stage: active
name: Default
